from pathlib import Path

rule all:
    input:
        "success.txt"

def next_step(wildcards, attempt):
    step_files = sorted(Path.cwd().glob("step*"))
    if len(step_files) == 0:
        return 1
    return int(step_files[-1].name.split("_")[-1]) + 1

rule run:
    output:
        "success.txt"
    resources:
        next_step=next_step
    shell:
        """
        touch start_{resources.next_step}
        for i in $(seq {resources.next_step} 6); do
            touch "step_$i"
            if [[ $i == 3 ]]; then
                exit 1
            fi
        done
        touch {output}
        """
