cluster-sync:
    mkdir -p logs &&
    nesi/submit.py
        --account {config[account]}
        --time {resources.time_min}
        --mem {resources.mem_mb}
        --cpus-per-task {resources.cpus}
        --gpus-per-node {resources.gpu}
        --output logs/slurm-%j-{rule}.out
        --error logs/slurm-%j-{rule}.out
        --job-name snakejob-{rule}
default-resources:
    - cpus=1
    - mem_mb=512
    - time_min=5
    - gpu=0
jobs: 1000
max-jobs-per-second: 10
local-cores: 1
latency-wait: 20
restart-times: 0
