cluster:
    mkdir -p logs &&
    sbatch
        --parsable
        --account {config[nesi_account]}
        --time {resources.time_min}
        --mem {resources.mem_mb}
        --cpus-per-task {resources.cpus}
        --gpus-per-node {resources.gpu}
        --output logs/%j-{rule}.out
        --error logs/%j-{rule}.out
        --job-name snakejob-{rule}
default-resources:
    - cpus=1
    - mem_mb=512
    - time_min=5
    - gpu=0
cluster-status: "slurm-status.py"
cluster-sidecar: "slurm-sidecar.py"
cluster-cancel: "scancel"
jobs: 1000
max-jobs-per-second: 10
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 20
restart-times: 0
use-conda: False
use-singularity: True
printshellcmds: False
