import pandas as pd


rule all:
    input:
        "result.txt"


def select_inputs(wildcards):
    files = pd.read_csv("conditions.csv")
    return files[files.include]["filename"]


rule combine:
    input:
        select_inputs
    output:
        "result.txt"
    shell:
        "cat {input} > {output}"
